# -- Poetry --
[tool.poetry]
name = "AioActors"
version = "2.3.0"
description = "Simple abstractions for actor model based on asyncio"
readme = "README.md"
repository = "https://gitlab.itpc.ru/libs/python/aioactors"
authors = ["Igor Voropaev <snakework10@gmail.com>"]
packages = [{ include = "aioactors" }]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[tool.poetry.group.linter.dependencies]

[tool.poetry.group.tests.dependencies]

[[tool.poetry.source]]
name = "wheels"
url = "https://pypi.itpc.dev/mirror/wheels.py311/+simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "all"
url = "https://pypi.itpc.dev/mirror/pypi.org/+simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "pypi"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# -- ruff -- 
[tool.ruff]
line-length = 135
preview = true

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "YTT",
    "ASYNC",
    "TRIO",
    "S",
    "BLE",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EXE",
    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "INT",
    "ARG",
    "PTH",
    "TD",
    "FIX",
    "ERA",
    "PD",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    "NPY",
    "AIR",
    "PERF",
    "FURB",
    "LOG",
    "RUF",
]
ignore = [
    "COM812",
    "ISC001",
    "TRY003",
    "PT013",
    "TID252",
    "RUF001",
    "RUF002",
    "RUF003",

]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "typings",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"typings" = ['typing', 'typing_extensions']

[tool.ruff.lint.pylint]
max-args = 15
max-returns = 10
max-branches = 30

# -- MyPy --
[tool.mypy]
ignore_missing_imports = true
exclude = ["__samples__"]

# -- Vulture --
[tool.vulture]
exclude = [".vscode/", "__samples__/", "tests"]

# -- PyTest --
[tool.pytest.ini_options]
asyncio_mode = "strict"

[tool.coverage.run]
omit = ["tests/*"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "def __repr__", "def __str__"]
