name: AioActors
version: 2.2.0
description: Simple abstractions for actor model based on asyncio
link: https://gitlab.itpc.ru/libs/python/aioactors
authors:
  - Igor Voropaev <snakework10@gmail.com>

service: aioactors
files:
  - pyproject.toml

images:
  compile: python:7

deps:
  python: ^3.10

linters:
  version: 9
tests:
  enabled: false

publish:
  name: libs
  url: https://pypi.itpc.dev/itpc/libs
